// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJWL6OmNARqTkZmsT5v6Y43Rb7xfaCG8o',
    appId: '1:935432551590:web:818ae7edc87a11e47b4867',
    messagingSenderId: '935432551590',
    projectId: 'placement-31b2c',
    authDomain: 'placement-31b2c.firebaseapp.com',
    storageBucket: 'placement-31b2c.appspot.com',
    measurementId: 'G-0W8F14P8FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRCq8Yw0w3pLuMojD9_kB_nVKcKMDGSY',
    appId: '1:935432551590:android:da1bd458412cdf6b7b4867',
    messagingSenderId: '935432551590',
    projectId: 'placement-31b2c',
    storageBucket: 'placement-31b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkV_CGwp-dgoTQAOxG2bjUROo5Q1HbMYQ',
    appId: '1:935432551590:ios:1b438fd4248780b07b4867',
    messagingSenderId: '935432551590',
    projectId: 'placement-31b2c',
    storageBucket: 'placement-31b2c.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkV_CGwp-dgoTQAOxG2bjUROo5Q1HbMYQ',
    appId: '1:935432551590:ios:bafed041753f3aa47b4867',
    messagingSenderId: '935432551590',
    projectId: 'placement-31b2c',
    storageBucket: 'placement-31b2c.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}